__author__ = 'diederik'

import compareSegments

#SC columns generated by jasper
sc_columns = [2,5,10,20]

#WordSXML
wordsXML = [[0,4, "a"], [4,8, "a"], [18,14, "c"], [14,20, "k"]]

#
comparator = compareSegments.Comparator()
print comparator.compare(sc_columns,wordsXML)
